CREATE SEQUENCE SEQU;
create table employee
(
    id          int GENERATED BY DEFAULT AS SEQUENCE SEQU PRIMARY KEY,
    firstname   varchar(32),
    lastname    varchar(32),
    email       varchar(32),
    phonenumber varchar(32),
    hiredate    date,
    salary      int
);